import type { Role } from '@/types/auth';
import {
  LayoutDashboard,
  FileText,
  Building2,
  MapPin,
  Receipt,
  BarChart3,
  UserCog,
  Users,
  CheckSquare,
  Settings,
  Shield,
  Plus,
  Clock,
  DollarSign,
  PlayCircle,
  List,
  XCircle,
  Copy,
  FileCheck,
  ClipboardList,
  type LucideIcon,
} from 'lucide-react';

export interface NavigationItem {
  id: string;
  label: string;
  href: string;
  icon: LucideIcon;
  roles?: Role[]; // Made optional for backward compatibility
  permissionCode?: string;
  permission?: {
    resource: string;
    action: string;
  };
  children?: NavigationItem[];
}

export const navigationItems: NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
    permissionCode: 'page.dashboard',
    permission: { resource: 'cases', action: 'read' }, // Using cases permission for dashboard access
  },
  {
    id: 'cases',
    label: 'Case Management',
    href: '/cases',
    icon: FileText,
    permissionCode: 'page.cases',
    permission: { resource: 'cases', action: 'read' },
    children: [
      {
        id: 'cases-new',
        label: 'Create New Case',
        href: '/cases/new',
        icon: Plus,
        permissionCode: 'page.cases',
        permission: { resource: 'cases', action: 'create' },
      },
      {
        id: 'cases-list',
        label: 'All Cases',
        href: '/cases',
        icon: FileText,
        permissionCode: 'page.cases',
        permission: { resource: 'cases', action: 'read' },
      },
      {
        id: 'dedupe',
        label: 'Dedupe',
        href: '/case-management/dedupe',
        icon: Copy,
        permissionCode: 'page.cases',
        permission: { resource: 'cases', action: 'read' },
      },
      {
        id: 'data-entry-dashboard',
        label: 'Data Entry',
        href: '/data-entry-dashboard',
        icon: ClipboardList,
        permissionCode: 'page.cases',
        permission: { resource: 'cases', action: 'read' },
      },
      {
        id: 'data-entry-mis',
        label: 'Data Entry MIS',
        href: '/data-entry-mis',
        icon: BarChart3,
        permissionCode: 'page.cases',
        permission: { resource: 'cases', action: 'read' },
      },
    ],
  },
  {
    id: 'tasks',
    label: 'Task Management',
    href: '/tasks',
    icon: CheckSquare,
    permissionCode: 'page.tasks',
    permission: { resource: 'tasks', action: 'read' },
    children: [
      {
        id: 'tasks-pending',
        label: 'Pending Tasks',
        href: '/tasks/pending',
        icon: Clock,
        permissionCode: 'page.tasks',
        permission: { resource: 'tasks', action: 'read' },
      },
      {
        id: 'tasks-revoked',
        label: 'Revoke Tasks',
        href: '/tasks/revoked',
        icon: XCircle,
        permissionCode: 'page.tasks',
        permission: { resource: 'tasks', action: 'read' },
      },
      {
        id: 'tasks-in-progress',
        label: 'In Progress Tasks',
        href: '/tasks/in-progress',
        icon: PlayCircle,
        permissionCode: 'page.tasks',
        permission: { resource: 'tasks', action: 'read' },
      },
      {
        id: 'tasks-revisit',
        label: 'Revisit Tasks',
        href: '/tasks/revisit',
        icon: Copy,
        permissionCode: 'page.tasks',
        permission: { resource: 'tasks', action: 'read' },
      },
      {
        id: 'tasks-completed',
        label: 'Completed Tasks',
        href: '/tasks/completed',
        icon: CheckSquare,
        permissionCode: 'page.tasks',
        permission: { resource: 'tasks', action: 'read' },
      },
      {
        id: 'tat-monitoring',
        label: 'TAT Monitoring',
        href: '/tasks/tat-monitoring',
        icon: Clock,
        permissionCode: 'page.tasks',
        permission: { resource: 'tasks', action: 'read' },
      },
      {
        id: 'tasks-all',
        label: 'All Tasks',
        href: '/tasks',
        icon: List,
        permissionCode: 'page.tasks',
        permission: { resource: 'tasks', action: 'read' },
      },
    ],
  },
  {
    id: 'kyc-verification',
    label: 'KYC Verification',
    href: '/kyc',
    icon: FileCheck,
    permissionCode: 'page.kyc',
    permission: { resource: 'kyc', action: 'read' },
    children: [
      {
        id: 'kyc-pending',
        label: 'Pending KYC',
        href: '/kyc/pending',
        icon: Clock,
        permissionCode: 'page.kyc',
        permission: { resource: 'kyc', action: 'read' },
      },
      {
        id: 'kyc-completed',
        label: 'Completed KYC',
        href: '/kyc/completed',
        icon: CheckSquare,
        permissionCode: 'page.kyc',
        permission: { resource: 'kyc', action: 'read' },
      },
      {
        id: 'kyc-all',
        label: 'All KYC',
        href: '/kyc',
        icon: List,
        permissionCode: 'page.kyc',
        permission: { resource: 'kyc', action: 'read' },
      },
    ],
  },
  {
    id: 'clients',
    label: 'Client Management',
    href: '/clients',
    icon: Building2,
    permissionCode: 'page.masterdata',
    permission: { resource: 'clients', action: 'read' },
    children: [
      {
        id: 'clients-list',
        label: 'Clients',
        href: '/clients',
        icon: Building2,
        permissionCode: 'page.masterdata',
        permission: { resource: 'clients', action: 'read' },
      },
      {
        id: 'products',
        label: 'Products',
        href: '/products',
        icon: Settings,
        permissionCode: 'page.masterdata',
        permission: { resource: 'products', action: 'read' },
      },
      {
        id: 'verification-types',
        label: 'Verification Types',
        href: '/verification-types',
        icon: CheckSquare,
        permissionCode: 'page.masterdata',
        permission: { resource: 'verificationTypes', action: 'read' },
      },
      {
        id: 'document-types',
        label: 'Document Types',
        href: '/document-types',
        icon: FileText,
        permissionCode: 'page.masterdata',
        permission: { resource: 'documentTypes', action: 'read' },
      },
      {
        id: 'data-entry-templates',
        label: 'Data Entry Templates',
        href: '/settings/case-data-templates',
        icon: FileText,
        permissionCode: 'page.settings',
        permission: { resource: 'settings', action: 'read' },
      },
      {
        id: 'report-templates',
        label: 'Report Templates',
        href: '/settings/report-templates',
        icon: FileText,
        // Gated on the manage permission so roles holding this perm (SUPER_ADMIN
        // + MANAGER today) see the menu item without also needing page.settings.
        // The route itself uses the same guard.
        permissionCode: 'report_template.manage',
        permission: { resource: 'settings', action: 'read' },
      },
    ],
  },
  {
    id: 'rate-management',
    label: 'Rate Management',
    href: '/rate-management',
    icon: DollarSign,
    permissionCode: 'page.masterdata',
    permission: { resource: 'rateManagement', action: 'read' },
    children: [
      {
        id: 'rate-types',
        label: 'Rate Types',
        href: '/rate-management/rate-types',
        icon: DollarSign,
        permissionCode: 'page.masterdata',
        permission: { resource: 'rateManagement', action: 'read' },
      },
      {
        id: 'service-zones',
        label: 'Service Zone Rules',
        href: '/rate-management/service-zones',
        icon: MapPin,
        permissionCode: 'page.masterdata',
        permission: { resource: 'rateManagement', action: 'read' },
      },
      {
        id: 'rate-type-assignments',
        label: 'Rate Type Assignment',
        href: '/rate-management/assignments',
        icon: Settings,
        permissionCode: 'page.masterdata',
        permission: { resource: 'rateManagement', action: 'read' },
      },
      {
        id: 'rate-amounts',
        label: 'Rate Amounts',
        href: '/rate-management/rates',
        icon: DollarSign,
        permissionCode: 'page.masterdata',
        permission: { resource: 'rateManagement', action: 'read' },
      },
      {
        id: 'rate-report',
        label: 'Rate Report',
        href: '/rate-management/report',
        icon: BarChart3,
        permissionCode: 'page.masterdata',
        permission: { resource: 'rateManagement', action: 'read' },
      },
      {
        id: 'document-type-rates',
        label: 'KYC Rates',
        href: '/rate-management/document-rates',
        icon: FileText,
        permissionCode: 'page.masterdata',
        permission: { resource: 'rateManagement', action: 'read' },
      },
    ],
  },
  {
    id: 'locations',
    label: 'Location Management',
    href: '/locations',
    icon: MapPin,
    permissionCode: 'page.masterdata',
    permission: { resource: 'locations', action: 'read' },
    children: [
      {
        id: 'countries',
        label: 'Countries',
        href: '/locations/countries',
        icon: MapPin,
        permissionCode: 'page.masterdata',
        permission: { resource: 'locations', action: 'read' },
      },
      {
        id: 'states',
        label: 'States',
        href: '/locations/states',
        icon: MapPin,
        permissionCode: 'page.masterdata',
        permission: { resource: 'locations', action: 'read' },
      },
      {
        id: 'cities',
        label: 'Cities',
        href: '/locations/cities',
        icon: MapPin,
        permissionCode: 'page.masterdata',
        permission: { resource: 'locations', action: 'read' },
      },
      {
        id: 'pincodes',
        label: 'Pincodes',
        href: '/locations/pincodes',
        icon: MapPin,
        permissionCode: 'page.masterdata',
        permission: { resource: 'locations', action: 'read' },
      },
      {
        id: 'areas',
        label: 'Areas',
        href: '/locations/areas',
        icon: MapPin,
        permissionCode: 'page.masterdata',
        permission: { resource: 'locations', action: 'read' },
      },
    ],
  },
  {
    id: 'billing',
    label: 'Billing & Commission',
    href: '/billing',
    icon: Receipt,
    permissionCode: 'page.billing',
    permission: { resource: 'billing', action: 'read' },
    children: [
      {
        id: 'invoices',
        label: 'Invoices',
        href: '/invoices',
        icon: Receipt,
        permissionCode: 'page.billing',
        permission: { resource: 'billing', action: 'read' },
      },
      {
        id: 'commissions',
        label: 'Commissions',
        href: '/commissions',
        icon: BarChart3,
        permissionCode: 'page.billing',
        permission: { resource: 'commissions', action: 'read' },
      },
      {
        id: 'commission-management',
        label: 'Commission Management',
        href: '/commission-management',
        icon: DollarSign,
        permissionCode: 'page.billing',
        permission: { resource: 'commissions', action: 'read' },
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports & MIS',
    href: '/reports',
    icon: BarChart3,
    permissionCode: 'page.reports',
    permission: { resource: 'reports', action: 'read' },
    children: [
      {
        id: 'analytics',
        label: 'Analytics Dashboard',
        href: '/analytics',
        icon: BarChart3,
        permissionCode: 'page.analytics',
        permission: { resource: 'analytics', action: 'read' },
      },
      {
        id: 'mis-dashboard',
        label: 'MIS Dashboard',
        href: '/reports/mis',
        icon: BarChart3,
        permissionCode: 'page.analytics',
        permission: { resource: 'analytics', action: 'read' },
      },
    ],
  },
  {
    id: 'user-management',
    label: 'User Management',
    href: '#',
    icon: UserCog,
    permissionCode: 'page.users',
    permission: { resource: 'users', action: 'read' },
    children: [
      {
        id: 'users',
        label: 'Users',
        href: '/users',
        icon: Users,
        permissionCode: 'page.users',
        permission: { resource: 'users', action: 'read' },
      },
      {
        id: 'users-activities',
        label: 'User Activity',
        href: '/users/activities',
        icon: List,
        permissionCode: 'page.users',
        permission: { resource: 'users', action: 'read' },
      },
      {
        id: 'users-sessions',
        label: 'User Sessions',
        href: '/users/sessions',
        icon: Clock,
        permissionCode: 'page.users',
        permission: { resource: 'users', action: 'read' },
      },
      {
        id: 'rbac-admin',
        label: 'RBAC Administration',
        href: '/admin/rbac',
        icon: Shield,
        permissionCode: 'page.rbac',
      },
      {
        id: 'field-monitoring',
        label: 'Field Monitoring',
        href: '/operations/field-monitoring',
        icon: MapPin,
        permissionCode: 'page.field_monitoring',
      },
    ],
  },
  // Form Viewer removed — unused (RBAC audit 2026-04-16)
  {
    id: 'security-ux',
    label: 'Security & UX',
    href: '/security-ux',
    icon: Shield,
    permissionCode: 'page.settings',
    permission: { resource: 'settings', action: 'read' },
  },
];
