export const RBAC_PERMISSION_MODULES = {
  'MOBILE (FIELD AGENT)': [
    'visit.start',
    'visit.upload',
    'visit.submit',
    'visit.revoke',
    'visit.revisit',
    'task.revoke',
    'case.view',
  ],
  PAGE: [
    'page.dashboard',
    'page.cases',
    'page.tasks',
    'page.reports',
    'page.billing',
    'page.users',
    'page.field_monitoring',
    'page.kyc',
    'page.rbac',
    'page.settings',
    'page.masterdata',
    'page.analytics',
  ],
  CASE: ['case.view', 'case.create', 'case.assign', 'case.reassign', 'case.update', 'case.delete'],
  VISIT: ['visit.start', 'visit.upload', 'visit.submit', 'visit.revoke', 'visit.revisit', 'task.revoke'],
  REVIEW: ['review.view', 'review.approve', 'review.rework'],
  REPORT: ['report.generate', 'report.download'],
  BILLING: ['billing.generate', 'billing.download', 'billing.approve'],
  'USER MANAGEMENT': [
    'user.view',
    'user.create',
    'user.update',
    'user.delete',
    'role.manage',
    'permission.manage',
    'territory.assign',
  ],
  SYSTEM: ['dashboard.view', 'settings.manage'],
} as const;

export const PAGE_PERMISSION_GUIDE = [
  { page: 'Dashboard', permissions: ['page.dashboard'] },
  { page: 'Case Management', permissions: ['page.cases'] },
  { page: 'Task Management / Review', permissions: ['page.tasks'] },
  { page: 'Reports', permissions: ['page.reports'] },
  { page: 'Analytics / MIS', permissions: ['page.analytics'] },
  { page: 'Billing / Commission', permissions: ['page.billing'] },
  { page: 'Users', permissions: ['page.users'] },
  { page: 'KYC Verification', permissions: ['page.kyc'] },
  { page: 'Field Executive Monitoring', permissions: ['page.field_monitoring'] },
  { page: 'RBAC Administration', permissions: ['page.rbac'] },
  { page: 'Master Data', permissions: ['page.masterdata'] },
  { page: 'Settings', permissions: ['page.settings'] },
] as const;

export const ROUTE_ACCESS_OPTIONS = [
  { key: 'mobile-app', label: 'Mobile App (Field Agent)' },
  { key: 'dashboard', label: 'Dashboard' },
  { key: 'cases', label: 'Cases' },
  { key: 'task-board', label: 'Task Board' },
  { key: 'visit-execution', label: 'Field Monitoring' },
  { key: 'review-qc', label: 'Review/QC' },
  { key: 'reports', label: 'Reports' },
  { key: 'billing', label: 'Billing' },
  { key: 'commission', label: 'Commission' },
  { key: 'users', label: 'Users' },
  { key: 'clients', label: 'Clients' },
  { key: 'products', label: 'Products' },
  { key: 'territory-mapping', label: 'Territory Mapping' },
  { key: 'settings', label: 'Settings' },
] as const;
