ALTER TABLE IF EXISTS users
  DROP CONSTRAINT IF EXISTS fk_users_role_id;

ALTER TABLE IF EXISTS users
  DROP COLUMN IF EXISTS "roleId";

DROP TABLE IF EXISTS roles CASCADE;

DROP SEQUENCE IF EXISTS roles_temp_id_seq;

