import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { BarChart3, Download, FileText, MoreHorizontal, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { reportsService } from '@/services/reports';
import { MISReport } from '@/types/reports';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/ui/components/alert-dialog';
import { Badge } from '@/ui/components/badge';
import { Button } from '@/ui/components/button';
import { Card, CardContent } from '@/ui/components/card';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/ui/components/dropdown-menu';
import { LoadingState } from '@/ui/components/loading';
import { Box } from '@/ui/primitives/Box';
import { Stack } from '@/ui/primitives/Stack';
import { Text } from '@/ui/primitives/Text';

interface MISReportsTableProps {
  data: MISReport[];
  isLoading: boolean;
}

const tableCellStyle = {
  padding: '0.85rem 1rem',
  borderBottom: '1px solid var(--ui-border)',
  verticalAlign: 'top' as const,
};

export function MISReportsTable({ data, isLoading }: MISReportsTableProps) {
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [reportToDelete, setReportToDelete] = useState<MISReport | null>(null);
  const queryClient = useQueryClient();

  const deleteMutation = useMutation({
    mutationFn: (id: string) => reportsService.deleteMISReport(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mis-reports'] });
      toast.success('Report deleted successfully');
      setShowDeleteDialog(false);
      setReportToDelete(null);
    },
    onError: (error: unknown) => {
      const message = error instanceof Error ? error.message : 'Failed to delete report';
      const axiosError = error as { response?: { data?: { message?: string } } };
      toast.error(axiosError.response?.data?.message || message);
    },
  });

  const handleDownload = async (report: MISReport, format: 'PDF' | 'EXCEL' | 'CSV' = 'PDF') => {
    try {
      const blob = await reportsService.downloadMISReport(report.id, format);
      const url = window.URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = `${report.title.replace(/\s+/g, '_')}_${format.toLowerCase()}.${format === 'EXCEL' ? 'xlsx' : format.toLowerCase()}`;
      anchor.click();
      window.URL.revokeObjectURL(url);
      toast.success('Report downloaded successfully');
    } catch {
      toast.error('Failed to download report');
    }
  };

  const confirmDelete = () => {
    if (reportToDelete) {
      deleteMutation.mutate(reportToDelete.id);
    }
  };

  const getReportTypeBadge = (type: string) => {
    const typeConfig = {
      TURNAROUND_TIME: { variant: 'accent' as const, label: 'Turnaround Time' },
      COMPLETION_RATE: { variant: 'warning' as const, label: 'Completion Rate' },
      PRODUCTIVITY: { variant: 'neutral' as const, label: 'Productivity' },
      QUALITY: { variant: 'info' as const, label: 'Quality' },
      FINANCIAL: { variant: 'positive' as const, label: 'Financial' },
    };
    const config = typeConfig[type as keyof typeof typeConfig] || { variant: 'neutral' as const, label: type };
    return <Badge variant={config.variant}>{config.label}</Badge>;
  };

  if (isLoading) {
    return <LoadingState message="Loading reports..." size="lg" />;
  }

  if (!data || data.length === 0) {
    return (
      <Stack gap={2} align="center" style={{ textAlign: 'center', padding: '3rem 0' }}>
        <BarChart3 size={48} style={{ color: 'var(--ui-text-muted)' }} />
        <Text as="h3" variant="title">No MIS reports found</Text>
        <Text tone="muted">Get started by generating your first MIS report.</Text>
      </Stack>
    );
  }

  return (
    <>
      <Box style={{ border: '1px solid var(--ui-border)', borderRadius: 'var(--ui-radius-lg)', overflow: 'hidden' }}>
        <Box style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', minWidth: '860px', borderCollapse: 'collapse', background: 'var(--ui-surface)' }}>
            <thead style={{ background: 'var(--ui-surface-muted)' }}>
              <tr>
                {['Report Title', 'Type', 'Description', 'Period', 'Generated By', 'Generated At', 'Actions'].map((header) => (
                  <th
                    key={header}
                    style={{
                      ...tableCellStyle,
                      textAlign: header === 'Actions' ? 'right' : 'left',
                      fontSize: '0.75rem',
                      letterSpacing: '0.08em',
                      textTransform: 'uppercase',
                      color: 'var(--ui-text-muted)',
                      fontWeight: 700,
                    }}
                  >
                    {header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.map((report) => (
                <tr key={report.id}>
                  <td style={tableCellStyle}>
                    <Stack direction="horizontal" gap={2} align="center">
                      <Box
                        style={{
                          width: '2rem',
                          height: '2rem',
                          borderRadius: '999px',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          background: 'rgba(17, 116, 110, 0.12)',
                          color: 'var(--ui-accent)',
                          flexShrink: 0,
                        }}
                      >
                        <FileText size={14} />
                      </Box>
                      <Text variant="body-sm">{report.title}</Text>
                    </Stack>
                  </td>
                  <td style={tableCellStyle}>{getReportTypeBadge(report.reportType)}</td>
                  <td style={tableCellStyle}>
                    <Text variant="body-sm" tone="muted">{report.description || 'No description'}</Text>
                  </td>
                  <td style={tableCellStyle}><Text variant="body-sm">{report.period}</Text></td>
                  <td style={tableCellStyle}><Text variant="body-sm">{report.generatedBy}</Text></td>
                  <td style={tableCellStyle}><Text variant="body-sm">{new Date(report.generatedAt).toLocaleDateString()}</Text></td>
                  <td style={{ ...tableCellStyle, textAlign: 'right' }}>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" style={{ paddingInline: '0.5rem' }} icon={<MoreHorizontal size={16} />} />
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuLabel>Actions</DropdownMenuLabel>
                        <DropdownMenuItem onClick={() => handleDownload(report, 'PDF')}>
                          <Stack direction="horizontal" gap={2} align="center">
                            <Download size={14} />
                            <span>Download PDF</span>
                          </Stack>
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handleDownload(report, 'EXCEL')}>
                          <Stack direction="horizontal" gap={2} align="center">
                            <Download size={14} />
                            <span>Download Excel</span>
                          </Stack>
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handleDownload(report, 'CSV')}>
                          <Stack direction="horizontal" gap={2} align="center">
                            <Download size={14} />
                            <span>Download CSV</span>
                          </Stack>
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem onClick={() => { setReportToDelete(report); setShowDeleteDialog(true); }}>
                          <Stack direction="horizontal" gap={2} align="center">
                            <Trash2 size={14} />
                            <span>Delete Report</span>
                          </Stack>
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Box>
      </Box>

      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Are you sure?</AlertDialogTitle>
            <AlertDialogDescription>
              This action cannot be undone. This will permanently delete the report &quot;{reportToDelete?.title}&quot;.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete} disabled={deleteMutation.isPending}>
              {deleteMutation.isPending ? 'Deleting...' : 'Delete'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
